sonar.projectKey=Isa-twaoos
sonar.projectName=Isa-twaoos
sonar.projectVersion=1.0

sonar.sources=my-api
sonar.exclusions=**/node_modules/**,**/.venv/**,**/test_temp.db,**/database.db,**/__pycache__/**,**/*.pyc,**/dist/**,**/.angular/**,**/backend-docs/**,**/alembic/**,**/tests/**

sonar.host.url=http://localhost:9000
sonar.token=sqp_896e2eb0c3c2c8645a4f0b4d1f321c59236a95e3

sonar.python.coverage.reportPaths=my-api/coverage.xml
sonar.coverage.exclusions=**/email_service.py,**/main.py,**/google_auth.py,**/database.py
sonar.python.version=3.11