"""add waitlist_position

Revision ID: b899357e36e3
Revises: 6f2b6e7e16f5
Create Date: 2026-05-01 12:58:00.525210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b899357e36e3'
down_revision: Union[str, Sequence[str], None] = '6f2b6e7e16f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_registrations', sa.Column('waitlist_position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_registrations', 'waitlist_position')
    # ### end Alembic commands ###
