"""add pending status and rejection_reason

Revision ID: bb837d1fc0d2
Revises: b899357e36e3
Create Date: 2026-05-02 17:41:14.763313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb837d1fc0d2'
down_revision: Union[str, Sequence[str], None] = 'b899357e36e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('rejection_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'rejection_reason')
    # ### end Alembic commands ###
